// import {
//   GetAllCommentsRequest,
//   AddCommentRequest,
//   UpdateCommentRequest,
//   DeleteCommentRequest,
//   LikeCommentRequest,
//   DislikeCommentRequest,
//   GetAllCommentsResponse,
//   AddCommentResponse,
//   UpdateCommentResponse,
//   DeleteCommentResponse,
//   LikeCommentResponse,
//   DislikeCommentResponse,
// } from './comments';
import * as CommentTypes from './comments';
import {
  GetPostByIdRequest,
  CreatePostRequest,
  UpdatePostRequest,
  DeletePostRequest,
  LikePostRequest,
  UnlikePostRequest,
  GetPostsResponse,
  GetPostByIdResponse,
  CreatePostResponse,
  UpdatePostResponse,
  DeletePostResponse,
  LikePostResponse,
  UnlikePostResponse,
} from './posts';
import {
  GetUserByIdRequest,
  UpdateUserDataRequest,
  GetFriendsRequest,
  AddFriendRequest,
  DeleteFriendRequest,
  RequestSendFriendRequest,
  RequestDeleteFriendRequest,
  GetAllUsersResponse,
  GetUserByIdResponse,
  UpdateUserDataResponse,
  DeleteUserResponse,
  GetFriendsResponse,
  AddFriendResponse,
  DeleteFriendResponse,
  SendFriendRequestResponse,
  GetFriendRequestsResponse,
  DeleteFriendRequestResponse,
} from './users';
import {
  LoginRequest,
  LoginResponse,
  LoginGoogleResponse,
  CreateAccountRequest,
  CreateAccountResponse,
  AuthenticateUserResponse,
} from './auth';
import { MissingBodyError, UnauthorizedError, BadRequestError } from './errors';
import {
  MySocket,
  ServerToClientEvents,
  ClientToServerEvents,
  InterServerEvents,
} from './sockets';

export {
  MySocket,
  ServerToClientEvents,
  ClientToServerEvents,
  InterServerEvents,
  CommentTypes,
  MissingBodyError,
  UnauthorizedError,
  BadRequestError,
  GetPostByIdRequest,
  CreatePostRequest,
  UpdatePostRequest,
  DeletePostRequest,
  LikePostRequest,
  UnlikePostRequest,
  GetPostsResponse,
  GetPostByIdResponse,
  CreatePostResponse,
  UpdatePostResponse,
  DeletePostResponse,
  LikePostResponse,
  UnlikePostResponse,
  GetUserByIdRequest,
  UpdateUserDataRequest,
  GetFriendsRequest,
  AddFriendRequest,
  DeleteFriendRequest,
  RequestSendFriendRequest,
  RequestDeleteFriendRequest,
  GetUserByIdResponse,
  GetAllUsersResponse,
  UpdateUserDataResponse,
  DeleteUserResponse,
  GetFriendsResponse,
  AddFriendResponse,
  DeleteFriendResponse,
  SendFriendRequestResponse,
  GetFriendRequestsResponse,
  DeleteFriendRequestResponse,
  LoginRequest,
  LoginResponse,
  LoginGoogleResponse,
  CreateAccountRequest,
  CreateAccountResponse,
  AuthenticateUserResponse,
};
